package gui;

import managers.UserManager;
import models.User;

import javax.swing.*;
import java.awt.*;

public class RegisterFrame extends JFrame {
    public RegisterFrame() {
        setTitle("Create New Account");
        setSize(400, 450);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setLayout(new BorderLayout());

        JLabel title = new JLabel("Create Your Account", SwingConstants.CENTER);
        title.setFont(new Font("Segoe UI", Font.BOLD, 20));
        title.setBorder(BorderFactory.createEmptyBorder(20, 0, 10, 0));
        add(title, BorderLayout.NORTH);

        JPanel form = new JPanel(new GridLayout(8, 2, 10, 10));
        form.setBorder(BorderFactory.createEmptyBorder(10, 30, 10, 30));

        JTextField firstName = new JTextField();
        JTextField lastName = new JTextField();
        JTextField email = new JTextField();
        JTextField phone = new JTextField();
        JTextField username = new JTextField();
        JPasswordField password = new JPasswordField();

        form.add(new JLabel("First Name:")); form.add(firstName);
        form.add(new JLabel("Last Name:")); form.add(lastName);
        form.add(new JLabel("Email:")); form.add(email);
        form.add(new JLabel("Phone:")); form.add(phone);
        form.add(new JLabel("Username:")); form.add(username);
        form.add(new JLabel("Password:")); form.add(password);

        JButton registerBtn = new JButton("Register");
        JButton cancelBtn = new JButton("Cancel");

        form.add(registerBtn);
        form.add(cancelBtn);

        add(form, BorderLayout.CENTER);

        registerBtn.addActionListener(e -> {
            User user = new User(
                0, // id auto-generated by DB
                firstName.getText(),
                lastName.getText(),
                email.getText(),
                phone.getText(),
                username.getText(),
                new String(password.getPassword()),
                "passenger"
            );

            boolean success = UserManager.getInstance().registerUser(user);
            if (success) {
                JOptionPane.showMessageDialog(this, "✅ Account created successfully!");
                dispose();
                new LoginFrame();
            } else {
                JOptionPane.showMessageDialog(this, "❌ Failed to create account.");
            }
        });

        cancelBtn.addActionListener(e -> {
            dispose();
            new LoginFrame();
        });

        setVisible(true);
    }
}
